import { ArrowRight, BookOpenCheck } from "lucide-react";
import { useState } from "react";
import { useCareerForgeJourney } from "./useCareerForgeJourney";

export function CanonicalProgress({ openLearn }: { openLearn: () => void }) {
  const view = useCareerForgeJourney();
  const [delivery, setDelivery] = useState<string | null>(null);
  if (view.state !== "ready" || !view.journey) return <section className="learning-canonical-summary"><p>{view.state === "loading" ? "Reading canonical learning progress…" : "Career Forge is unavailable; no specimen progress is shown."}</p></section>;
  const { progress } = view.journey;
  return <section className="canonical-projection" aria-label="Canonical learning progress"><div className="canonical-projection-heading"><div><span className="eyebrow">CAREER FORGE / CANONICAL PROGRESS</span><h2>Evidence and next steps</h2><p>Friday reports recorded attempts and evidence, not invented completion percentages.</p></div><BookOpenCheck size={22} aria-hidden="true" /></div><p className="canonical-next-action">{progress.next_action}</p>{delivery && <p className="canonical-next-action">{delivery}</p>}<div className="canonical-progress-counts"><span><strong>{progress.recent_attempts.length}</strong> recent attempts</span><span><strong>{progress.evidence.length}</strong> evidence records</span><span><strong>{progress.assistance.length}</strong> assistance records</span><span><strong>{progress.unresolved_retries.length}</strong> retries to resolve</span></div><div className="canonical-progress-columns"><section><h3>Recent attempts</h3>{progress.recent_attempts.length ? <ol className="canonical-record-list">{progress.recent_attempts.map((attempt) => <li key={attempt.attempt_id}><strong>{attempt.competency_id} · {attempt.evaluation}</strong><span>Attempt {attempt.attempt_order}{attempt.retry_needed ? " · retry needed" : ""}</span>{attempt.feedback && <p>{attempt.feedback}</p>}<small>{attempt.evidence_type ?? "no evidence"} · {attempt.assistance_level ?? "no assistance"}</small></li>)}</ol> : <p>No canonical attempts are recorded yet.</p>}</section><section><h3>Scheduled review</h3>{progress.retention_reviews.length ? <ol className="canonical-record-list">{progress.retention_reviews.map((review) => <li key={review.review_id}><strong>{review.competency_id} · {review.state}</strong><span>Due {new Date(review.due_at).toLocaleDateString()}</span><small>Scheduled from {review.mastery} evidence; completion is not claimed.</small>{review.state === "scheduled" && new Date(review.due_at) <= new Date() && <button className="text-link" onClick={() => void view.deliverReview(review.review_id).then((prompt) => setDelivery(`Review prompt: ${prompt}`)).catch(() => setDelivery("Friday could not deliver this review. No learning state was changed."))}>Begin review</button>}</li>)}</ol> : <p>No evidence-backed review is scheduled yet.</p>}</section><section><h3>Learning history</h3>{progress.history.length ? <ol className="canonical-record-list">{progress.history.map((event, index) => <li key={`${event.occurred_at}-${index}`}><strong>{event.kind}</strong><span>{event.summary}</span>{event.retry_needed && <small>Retry needed</small>}</li>)}</ol> : <p>No learning history is recorded yet.</p>}</section></div><button className="text-link" onClick={openLearn}>Continue with Friday <ArrowRight size={14} /></button></section>;
}
