import { lazy, Suspense, useEffect, useRef, useState, useSyncExternalStore } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, ArrowUpRight, AudioLines, Bell, BookOpen, Braces, Check, ChevronDown, Command, Eye, Fingerprint, GitBranch, Layers3, Library, LoaderCircle, MessageSquare, MoreHorizontal, Orbit, Search, ShieldCheck, Sparkles, Workflow, X } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import type { CognitiveState, VisionView } from './types';
import { useStoredState } from './useStoredState';
import NeuralPresence from './NeuralPresence';
import './Vision.css';
import { FridayRuntimeStore } from '../runtime';
const Learning = lazy(()=>import('./Learning').then(m=>({default:m.Learning})));
const Operations = lazy(()=>import('./Operations').then(m=>({default:m.Operations})));

const destinations: {id:VisionView;label:string;description:string;icon:LucideIcon;group:string}[] = [
 {id:'home',label:'Friday',description:'A little room to think',icon:Orbit,group:'Your space'},
 {id:'conversation',label:'Conversation',description:'Think something through',icon:AudioLines,group:'Your space'},
 {id:'learn',label:'Career Forge',description:'Your ongoing apprenticeship',icon:BookOpen,group:'Grow'},
 {id:'lab',label:'Practice Lab',description:'An idea, made executable',icon:Braces,group:'Grow'},
 {id:'map',label:'Knowledge map',description:'See how it connects',icon:GitBranch,group:'Grow'},
 {id:'projects',label:'Career projects',description:'Build evidence that evolves with you',icon:Workflow,group:'Grow'},
 {id:'interview',label:'Interview mode',description:'Reason without hints',icon:MessageSquare,group:'Grow'},
 {id:'progress',label:'Progress & evidence',description:'What you have demonstrated',icon:Layers3,group:'Grow'},
 {id:'research',label:'Research',description:'Follow a question to its sources',icon:Library,group:'Understand'},
 {id:'memory',label:'Memory',description:'The things worth remembering',icon:Fingerprint,group:'Understand'},
 {id:'objectives',label:'Objectives',description:'Work with a clear intention',icon:Workflow,group:'Act'},
 {id:'automations',label:'Notifications',description:'Canonical events and watch status',icon:Bell,group:'Act'},
 {id:'perception',label:'Perception',description:'Give Friday a closer look',icon:Eye,group:'Act'},
 {id:'system',label:'Local intelligence',description:'Your machine. Your control.',icon:ShieldCheck,group:'Control'},
];
const cognitiveCopy:Record<CognitiveState,{label:string;detail:string}>={
 idle:{label:'Present',detail:'A quiet mind. Ready when you are.'}, listening:{label:'Listening',detail:'Take your time. I’m with you.'},thinking:{label:'Connecting',detail:'Finding the thread between ideas.'},speaking:{label:'Speaking',detail:'Turning a thought into words.'},working:{label:'Working',detail:'One considered step at a time.'},waiting:{label:'Your call',detail:'A decision only you should make.'},error:{label:'Needs attention',detail:'Something interrupted the thread.'},focus:{label:'Deep focus',detail:'One thing. All our attention.'}
};
const fridayRuntime = new FridayRuntimeStore();
function Logo(){return <svg width="26" height="30" viewBox="0 0 26 30" fill="none" aria-hidden="true"><path d="M13 1v28M2 7l22 16M24 7L2 23" stroke="currentColor" strokeWidth="1.2"/><path d="M13 1L24 7v16l-11 6-11-6V7L13 1Z" stroke="currentColor" opacity=".35"/><circle cx="13" cy="15" r="3" fill="currentColor"/></svg>}
function inline(text:string):ReactNode[]{return text.split(/(\*\*.*?\*\*|`[^`]+`)/g).map((s,i)=>s.startsWith('**')?<strong key={i}>{s.slice(2,-2)}</strong>:s.startsWith('`')?<code key={i}>{s.slice(1,-1)}</code>:s);}
function RichText({text}:{text:string}){return <div className="rich-text">{text.split(/(```[\s\S]*?```)/g).map((part,i)=>part.startsWith('```')?<div className="answer-code" key={i}><span>PYTHON</span><pre><code>{part.replace(/^```\w*\n?/, '').replace(/```$/, '')}</code></pre></div>:part.split('\n\n').filter(Boolean).map((p,j)=><p key={`${i}-${j}`}>{inline(p)}</p>))}</div>}
function useEscape(onClose:()=>void){useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[onClose]);}
function Modal({label,children,onClose,wide=false}:{label:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
 const ref=useRef<HTMLDivElement>(null); const returnFocus=useRef(document.activeElement as HTMLElement|null);
 useEscape(onClose);
 useEffect(()=>{const before=returnFocus.current;const node=ref.current;const focusable=()=>node?.querySelectorAll<HTMLElement>('button:not([disabled]),input,textarea,select,[tabindex="0"]');focusable()?.[0]?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const all=focusable();if(!all?.length)return;const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}};node?.addEventListener('keydown',trap);return()=>{node?.removeEventListener('keydown',trap);before?.focus();};},[]);
 return <div className="modal-scrim" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div ref={ref} className={`modal-surface ${wide?'modal-wide':''}`} role="dialog" aria-modal="true" aria-label={label}>{children}</div></div>;
}

export default function Vision(){
 const getRoute=():VisionView=>{const key=location.hash.slice(1);return destinations.some(d=>d.id===key)?key as VisionView:'home';};
 const [view,setView]=useState<VisionView>(getRoute);
 const [cognition,setCognition]=useState<CognitiveState>('idle');
 const [explore,setExplore]=useState(false),[query,setQuery]=useState('');
 const [attention,setAttention]=useState(false),[review,setReview]=useState(false);
 const [approved,setApproved]=useStoredState('global-approval',false);
 const [stateMenu,setStateMenu]=useState(false),[info,setInfo]=useState(false);
 const [toast,setToast]=useState(''); const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const runtime=useSyncExternalStore(fridayRuntime.subscribe.bind(fridayRuntime),fridayRuntime.getSnapshot.bind(fridayRuntime));
 const messages=runtime.conversation;
 const [prompt,setPrompt]=useState(''),[sending,setSending]=useState(false);
 const streaming=sending||messages.at(-1)?.status==='streaming';
 const runtimeReady=useRef<Promise<void>|null>(null);
 const readEnd=useRef<HTMLDivElement>(null); const input=useRef<HTMLTextAreaElement>(null);
 const current=destinations.find(d=>d.id===view)!;
 const workProps={navigate,notify,setCognition};
 function notify(text:string){setToast(text);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4300);}
 function navigate(next:VisionView){setView(next);setExplore(false);setQuery('');setStateMenu(false);if(!streaming)setCognition(next==='lab'?'focus':'idle');}
 useEffect(()=>{if(location.hash!==`#${view}`)location.hash=view;},[view]);
 useEffect(()=>{const update=()=>setView(getRoute());window.addEventListener('hashchange',update);const key=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setExplore(v=>!v);} if(event.key==='Escape')setStateMenu(false);};window.addEventListener('keydown',key);return()=>{window.removeEventListener('hashchange',update);window.removeEventListener('keydown',key);};},[]);
 useEffect(()=>{const controller=new AbortController();runtimeReady.current=fridayRuntime.start(controller.signal).catch(()=>{});return()=>{controller.abort();fridayRuntime.stop();};},[]);
 useEffect(()=>()=>{if(toastTimer.current)clearTimeout(toastTimer.current);},[]);
 function send(text:string){const value=text.trim();if(!value||streaming)return;setPrompt('');navigate('conversation');setCognition('thinking');setSending(true);void (runtimeReady.current??Promise.resolve()).then(()=>fridayRuntime.sendConversation({prompt:value})).catch(()=>{}).finally(()=>{setSending(false);setCognition('idle');});}
 function renderComposer(home=false) {return <form className={`thought-composer ${home?'home-composer':''}`} onSubmit={(e:FormEvent)=>{e.preventDefault();send(prompt);}}><div className="composer-entry"><Sparkles size={17}/><textarea ref={input} value={prompt} onChange={e=>setPrompt(e.target.value)} rows={1} placeholder={home?'A question. An idea. A place to begin.':'Stay with the thought…'} aria-label="Message Friday" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(prompt);}}}/>{streaming?<button className="composer-send" type="button" disabled aria-label="Friday is responding"><LoaderCircle size={15} className="op-spinning"/></button>:<button className="composer-send" type="submit" disabled={!prompt.trim()} aria-label="Send message"><ArrowUp size={18}/></button>}</div><div className="composer-meta"><span>{home?'Local Friday runtime · active session differs from durable memory':`Friday runtime ${runtime.connectionState}`}</span><kbd>↵</kbd></div>{runtime.error&&<p role="alert" className="runtime-error">Friday could not complete this request: {runtime.error}</p>}</form>;}
 const learnView=['learn','map','lab','projects','interview','progress'].includes(view);
 return <div className={`vision-app view-${view}`} data-cognition={cognition}>
  <header className="app-header">
   <button className="brand" onClick={()=>navigate('home')} aria-label="Friday home"><Logo/><span>FRIDAY<span className="brand-dot">.</span></span></button>
   <span className="header-rule"/>
   <button className="explore-button" onClick={()=>setExplore(true)}><span>Explore</span><ChevronDown size={13}/><kbd>⌘ K</kbd></button>
   <div className="header-location">{view==='home'?'PERSONAL COGNITIVE SYSTEM':current.label.toUpperCase()}</div>
   <button className="prototype-label" onClick={()=>setInfo(true)}><i/>ASTRA VISION<span>LOCAL PRESENTATION</span></button>
   <button className="icon-button attention-button" onClick={()=>setAttention(true)} aria-label="Open attention and approvals"><Bell size={18}/>{!approved&&<i/>}</button>
   <button className="avatar" onClick={()=>navigate('system')} aria-label="Your settings">R</button>
  </header>
  <div className={`presence-field ${view!=='home'?'presence-away':''}`} aria-hidden={view!=='home'}><div className="presence-aura"/><NeuralPresence state={cognition} visible={view==='home'}/></div>
  {view==='home'?<main className="home-view">
   <div className="home-coordinate"><span>01 / PRESENCE</span><span>ALWAYS YOURS.</span></div>
   <section className="home-greeting"><div className="eyebrow"><span className="tiny-line"/> A MIND AT YOUR SIDE</div><h1>Good evening,<br/><span>Rishav.</span></h1><p>There’s room for your next idea.</p><button className="home-continue" onClick={()=>navigate('conversation')}><span className="continue-symbol"><AudioLines size={20}/></span><span><small>YOUR FRIDAY SESSION</small><strong>{runtime.sessionActive?'Continue the conversation':'Start a conversation'}</strong><em>{runtime.sessionActive?`${runtime.sessionId||'Active session'} · temporary context`:'Local Qwen · grounded Friday runtime'}</em></span><ArrowUpRight size={20}/></button></section>
   <div className="presence-caption"><span className="presence-indicator"/><strong>{cognitiveCopy[cognition].label}</strong><span>{cognitiveCopy[cognition].detail}</span><button onClick={()=>setStateMenu(v=>!v)} aria-label="Explore cognitive states"><MoreHorizontal size={18}/></button></div>
   <div className="home-lower">{renderComposer(true)}<nav className="home-paths" aria-label="Start a workspace"><button onClick={()=>navigate('learn')}><BookOpen size={16}/>Learn something<ArrowUpRight size={13}/></button><button onClick={()=>navigate('lab')}><Braces size={16}/>Make it work<ArrowUpRight size={13}/></button><button onClick={()=>navigate('research')}><Library size={16}/>Follow a question<ArrowUpRight size={13}/></button></nav></div>
   <footer className="home-footer"><span><span className="local-dot"/> ON YOUR MACHINE. ON YOUR TERMS.</span><button onClick={()=>setStateMenu(v=>!v)}>Explore the cognitive states <ArrowRight size={13}/></button><span>FRIDAY / VISION 01</span></footer>
  </main>:view==='conversation'?<main className="conversation-view workspace-enter">
   <header className="conversation-heading"><div><button className="back-link" onClick={()=>navigate('home')}><ArrowLeft size={14}/>Back to presence</button><h1>A thread worth following.</h1></div><span className="runtime-connection">Friday runtime · {runtime.connectionState}</span></header>
   <div className="conversation-scroll"><div className="thread-date"><span/>TODAY · A CONVERSATION WITH FRIDAY<span/></div>{messages.length===0?<div className="conversation-empty"><Logo/><h2>Where should we begin?</h2><p>A question is enough.</p><button className="text-link" onClick={()=>send('Explain Python defaults')}>Explore a Python idea<ArrowUpRight size={15}/></button></div>:messages.map(message=><article className={`conversation-turn turn-${message.role==='assistant'?'friday':'user'}`} key={message.id}><div className="turn-label">{message.role==='assistant'?<Logo/>:<span className="author-mark">R</span>}<span>{message.role==='assistant'?'FRIDAY':'YOU'}{message.role==='assistant'&&<small>LOCAL FRIDAY RUNTIME</small>}</span></div>{!message.text?<div className="thinking-dots"><i/><i/><i/><span>Finding the thread…</span></div>:<RichText text={message.text}/>}</article>)}<div ref={readEnd}/>{!streaming&&messages.length>0&&<div className="conversation-next"><span>TAKE THE THOUGHT FURTHER</span><button onClick={()=>navigate('learn')}>Continue in Career Forge<ArrowUpRight size={14}/></button><button onClick={()=>navigate('lab')}>Try it in Practice Lab<ArrowUpRight size={14}/></button></div>}</div>
   <div className="conversation-bottom"><button className="jump-latest" onClick={()=>readEnd.current?.scrollIntoView({behavior:'smooth'})} aria-label="Jump to latest message"><ArrowDown size={15}/></button>{renderComposer()}</div>
  </main>:<main className={`workspace-host workspace-enter ${view==='lab'?'studio-host':''}`} key={view}><div className="workspace-topline"><button className="back-link" onClick={()=>navigate('home')}><ArrowLeft size={14}/>Friday</button><span>/</span><span>{learnView?'CAREER FORGE':current.group.toUpperCase()}</span><div className="workspace-presence"><i/>{cognitiveCopy[cognition].label}<button onClick={()=>navigate('conversation')}><AudioLines size={14}/><span>Talk to Friday</span></button></div></div><Suspense fallback={<div className="workspace-loading"><LoaderCircle size={20}/>Opening your workspace…</div>}>{learnView?<Learning view={view as 'learn'|'map'|'lab'|'projects'|'interview'|'progress'} {...workProps}/>:<Operations view={view as 'memory'|'research'|'objectives'|'automations'|'perception'|'system'} {...workProps}/>}</Suspense></main>}
  {stateMenu&&<div className="cognitive-menu"><div className="menu-heading"><span>COGNITIVE STATES</span><button className="icon-button" aria-label="Close cognitive states" onClick={()=>setStateMenu(false)}><X size={15}/></button></div><p>Explore how a thought takes shape.</p>{(Object.keys(cognitiveCopy) as CognitiveState[]).map(state=><button key={state} aria-pressed={state===cognition} onClick={()=>setCognition(state)}><span className={`state-glyph glyph-${state}`}><i/><i/><i/></span><span><strong>{cognitiveCopy[state].label}</strong><small>{state==='idle'?'Idle':state==='focus'?'Deep focus':state[0].toUpperCase()+state.slice(1)}</small></span>{state===cognition&&<Check size={15}/>}</button>)}<small className="demo-footnote">Visual state preview · no runtime action</small></div>}
  {explore&&<Modal label="Explore Friday" wide onClose={()=>setExplore(false)}><div className="explore-search"><Search size={21}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Where would you like to go?" aria-label="Search workspaces"/><button className="key-button" onClick={()=>setExplore(false)}>ESC</button></div><div className="explore-body"><div className="destination-list">{destinations.filter(d=>`${d.label} ${d.description} ${d.group}`.toLowerCase().includes(query.toLowerCase())).map((d,i,all)=><div key={d.id}>{(i===0||d.group!==all[i-1].group)&&<div className="nav-group-label">{d.group}</div>}<button className={view===d.id?'selected':''} onClick={()=>navigate(d.id)}><d.icon size={19}/><span><strong>{d.label}</strong><small>{d.description}</small></span><ArrowUpRight size={15}/></button></div>)}{destinations.filter(d=>`${d.label} ${d.description} ${d.group}`.toLowerCase().includes(query.toLowerCase())).length===0&&<p className="no-results">No workspace matches. Try “learn”, “memory”, or “research”.</p>}</div><aside className="explore-aside"><div className="eyebrow">YOUR CONTINUING STORY</div><div className="explore-orbit"><Logo/></div><h2>Small steps.<br/>Deeper understanding.</h2><p>Your learning, ideas, and work share one space.</p><button className="text-link" onClick={()=>navigate('learn')}>Resume your mission<ArrowRight size={16}/></button><div className="explore-note"><ShieldCheck size={18}/><p>Text conversation and Career Forge use Friday’s local canonical services. Several other Astra workspaces remain browser-local prototypes.</p></div></aside></div><div className="explore-footer"><span><Command size={12}/> K to explore · Escape to return</span><span>ONE FRIDAY. MANY POSSIBILITIES.</span></div></Modal>}
  {attention&&<Modal label="Your attention" onClose={()=>{setAttention(false);setReview(false);}}><div className="drawer-heading"><div className="eyebrow">JUST WHAT MATTERS</div><button className="icon-button" aria-label="Close attention" onClick={()=>{setAttention(false);setReview(false);}}><X size={19}/></button></div><div className="attention-content"><Bell size={25}/><h2>Your attention.</h2><p>One considered decision. The rest can wait.</p>{!approved?<div className="attention-item"><span className="status status-amber"><i/>Your decision</span><h3>Open the research source?</h3><p>Friday has prepared a browser action for a source in your research notebook.</p>{review?<div className="approval-preview"><div className="detail-row"><span>Action</span><span>Open website</span></div><div className="detail-row"><span>Destination</span><span>docs.python.org</span></div><div className="detail-row"><span>Authority</span><span>This action only</span></div><p>No website will open in this prototype.</p><div className="button-row"><button className="btn btn-primary" onClick={()=>{setApproved(true);setReview(false);notify('Demo action approved · nothing was opened or executed');}}>Approve preview<Check size={16}/></button><button className="btn" onClick={()=>{setApproved(true);setReview(false);notify('Demo action declined');}}>Decline</button></div></div>:<button className="text-link" onClick={()=>setReview(true)}>Review the action<ArrowUpRight size={16}/></button>}</div>:<div className="attention-resolved"><Check size={28}/><h3>Nothing needs a decision.</h3><p>Your demonstration decision has been recorded locally.</p><button className="text-link" onClick={()=>setApproved(false)}>Reset this preview</button></div>}<div className="attention-event"><span className="tiny-line"/><div><small>LEARNING · EARLIER TODAY</small><p>A new piece of evidence is ready to explore.</p><button className="text-link" onClick={()=>{setAttention(false);navigate('progress');}}>See your progress<ArrowUpRight size={14}/></button></div></div></div></Modal>}
  {info&&<Modal label="About this vision" onClose={()=>setInfo(false)}><div className="drawer-heading"><div className="eyebrow">ASTRA VISION / 01</div><button className="icon-button" aria-label="Close about" onClick={()=>setInfo(false)}><X size={18}/></button></div><div className="about-content"><Logo/><h2>One Friday.<br/>An open possibility.</h2><p>This Astra workspace combines Friday-backed Conversation, Career Forge, Memory, Research, Objectives / Activity, Notifications, and Perception with remaining prototype surfaces. Perception projects explicit local capture metadata and bounded observations; it grants no desktop-control authority.</p><p>Astra sends text through Friday’s existing conversation service and does not call a model directly. This page does not request microphone access; voice remains with Friday’s production voice service. Perception never attaches screen context to ordinary Conversation automatically. Prototype code and action outcomes are not executed.</p><div className="about-links"><span>Current Friday</span><a href="http://localhost:5173" target="_blank" rel="noreferrer">localhost:5173<ArrowUpRight size={14}/></a></div><button className="btn btn-primary" onClick={()=>setInfo(false)}>Explore the vision<ArrowRight size={16}/></button></div></Modal>}

  {toast&&<div className="toast" role="status"><Check size={16}/><span>{toast}</span><button onClick={()=>setToast('')} aria-label="Dismiss notification"><X size={14}/></button></div>}
 </div>;
}
