import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, ArrowUpRight, AudioLines, Bell, BookOpen, Braces, Check, ChevronDown, CircleDot, Command, Eye, Fingerprint, GitBranch, Layers3, Library, ListFilter, LoaderCircle, MoreHorizontal, Orbit, Plus, Search, ShieldCheck, Sparkles, Square, Workflow, X } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import type { CognitiveState, VisionView } from './types';
import { useStoredState } from './ui';
import NeuralPresence from './NeuralPresence';
import './Vision.css';
const Learning = lazy(()=>import('./Learning').then(m=>({default:m.Learning})));
const Operations = lazy(()=>import('./Operations').then(m=>({default:m.Operations})));

const destinations: {id:VisionView;label:string;description:string;icon:LucideIcon;group:string}[] = [
 {id:'home',label:'Friday',description:'A little room to think',icon:Orbit,group:'Your space'},
 {id:'conversation',label:'Conversation',description:'Think something through',icon:AudioLines,group:'Your space'},
 {id:'learn',label:'Career Forge',description:'Your ongoing apprenticeship',icon:BookOpen,group:'Grow'},
 {id:'lab',label:'Practice Lab',description:'An idea, made executable',icon:Braces,group:'Grow'},
 {id:'map',label:'Knowledge map',description:'See how it connects',icon:GitBranch,group:'Grow'},
 {id:'progress',label:'Progress & evidence',description:'What you have demonstrated',icon:Layers3,group:'Grow'},
 {id:'research',label:'Research',description:'Follow a question to its sources',icon:Library,group:'Understand'},
 {id:'memory',label:'Memory',description:'The things worth remembering',icon:Fingerprint,group:'Understand'},
 {id:'objectives',label:'Objectives',description:'Work with a clear intention',icon:Workflow,group:'Act'},
 {id:'automations',label:'Rhythms',description:'Thoughtful routines and events',icon:CircleDot,group:'Act'},
 {id:'perception',label:'Perception',description:'Give Friday a closer look',icon:Eye,group:'Act'},
 {id:'system',label:'Local intelligence',description:'Your machine. Your control.',icon:ShieldCheck,group:'Control'},
];
const cognitiveCopy:Record<CognitiveState,{label:string;detail:string}>={
 idle:{label:'Present',detail:'A quiet mind. Ready when you are.'}, listening:{label:'Listening',detail:'Take your time. I’m with you.'},thinking:{label:'Connecting',detail:'Finding the thread between ideas.'},speaking:{label:'Speaking',detail:'Turning a thought into words.'},working:{label:'Working',detail:'One considered step at a time.'},waiting:{label:'Your call',detail:'A decision only you should make.'},error:{label:'Needs attention',detail:'Something interrupted the thread.'},focus:{label:'Deep focus',detail:'One thing. All our attention.'}
};
const initialMessages:Message[]=[
 {id:'sample-1',role:'user',text:'Why do small defaults sometimes create surprising bugs?'},
 {id:'sample-2',role:'friday',text:'Often, it’s a question of **when something is created**.\n\nA function’s default arguments are evaluated once, when Python defines the function. If that default is a list, later calls share the very same object.\n\nThe useful mental model: a default is something the function already owns, not a recipe it follows each time.\n\n```python\ndef collect(item, bucket=None):\n    if bucket is None:\n        bucket = []  # a fresh list for this call\n    bucket.append(item)\n    return bucket\n```\n\nThe next interesting question is yours: what should happen when a caller deliberately passes an existing list?',context:'Python foundations · Example conversation'},
];
interface Message { id:string;role:'user'|'friday';text:string;context?:string;interrupted?:boolean }
function Logo(){return <svg width="26" height="30" viewBox="0 0 26 30" fill="none" aria-hidden="true"><path d="M13 1v28M2 7l22 16M24 7L2 23" stroke="currentColor" strokeWidth="1.2"/><path d="M13 1L24 7v16l-11 6-11-6V7L13 1Z" stroke="currentColor" opacity=".35"/><circle cx="13" cy="15" r="3" fill="currentColor"/></svg>}
function inline(text:string):ReactNode[]{return text.split(/(\*\*.*?\*\*|`[^`]+`)/g).map((s,i)=>s.startsWith('**')?<strong key={i}>{s.slice(2,-2)}</strong>:s.startsWith('`')?<code key={i}>{s.slice(1,-1)}</code>:s);}
function RichText({text}:{text:string}){return <div className="rich-text">{text.split(/(```[\s\S]*?```)/g).map((part,i)=>part.startsWith('```')?<div className="answer-code" key={i}><span>PYTHON</span><pre><code>{part.replace(/^```\w*\n?/, '').replace(/```$/, '')}</code></pre></div>:part.split('\n\n').filter(Boolean).map((p,j)=><p key={`${i}-${j}`}>{inline(p)}</p>))}</div>}
function useEscape(onClose:()=>void){useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[onClose]);}
function Modal({label,children,onClose,wide=false}:{label:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
 const ref=useRef<HTMLDivElement>(null); const returnFocus=useRef(document.activeElement as HTMLElement|null);
 useEscape(onClose);
 useEffect(()=>{const before=returnFocus.current;const node=ref.current;const focusable=()=>node?.querySelectorAll<HTMLElement>('button:not([disabled]),input,textarea,select,[tabindex="0"]');focusable()?.[0]?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const all=focusable();if(!all?.length)return;const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}};node?.addEventListener('keydown',trap);return()=>{node?.removeEventListener('keydown',trap);before?.focus();};},[]);
 return <div className="modal-scrim" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div ref={ref} className={`modal-surface ${wide?'modal-wide':''}`} role="dialog" aria-modal="true" aria-label={label}>{children}</div></div>;
}

export default function Vision(){
 const getRoute=():VisionView=>{const key=location.hash.slice(1);return destinations.some(d=>d.id===key)?key as VisionView:'home';};
 const [view,setView]=useState<VisionView>(getRoute);
 const [cognition,setCognition]=useState<CognitiveState>('idle');
 const [explore,setExplore]=useState(false),[query,setQuery]=useState('');
 const [attention,setAttention]=useState(false),[review,setReview]=useState(false);
 const [approved,setApproved]=useStoredState('global-approval',false);
 const [stateMenu,setStateMenu]=useState(false),[info,setInfo]=useState(false),[history,setHistory]=useState(false);
 const [toast,setToast]=useState(''); const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [messages,setMessages]=useStoredState<Message[]>('conversation',initialMessages);
 const [prompt,setPrompt]=useState(''),[streaming,setStreaming]=useState(false),[voiceDemo,setVoiceDemo]=useState(false);
 const streamTimer=useRef<ReturnType<typeof setInterval>|null>(null),stageTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const readEnd=useRef<HTMLDivElement>(null); const input=useRef<HTMLTextAreaElement>(null);
 const current=destinations.find(d=>d.id===view)!;
 const workProps={navigate,notify,setCognition};
 function notify(text:string){setToast(text);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4300);}
 function navigate(next:VisionView){setView(next);location.hash=next;setExplore(false);setQuery('');setStateMenu(false);if(!streaming)setCognition(next==='lab'?'focus':'idle');}
 useEffect(()=>{const update=()=>setView(getRoute());window.addEventListener('hashchange',update);const key=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setExplore(v=>!v);} if(event.key==='Escape')setStateMenu(false);};window.addEventListener('keydown',key);return()=>{window.removeEventListener('hashchange',update);window.removeEventListener('keydown',key);};},[]);
 useEffect(()=>()=>{if(streamTimer.current)clearInterval(streamTimer.current);if(stageTimer.current)clearTimeout(stageTimer.current);if(toastTimer.current)clearTimeout(toastTimer.current);},[]);
 function interrupt(){if(streamTimer.current)clearInterval(streamTimer.current);if(stageTimer.current)clearTimeout(stageTimer.current);setStreaming(false);setVoiceDemo(false);setCognition('idle');setMessages(old=>old.map((m,i)=>i===old.length-1&&m.role==='friday'?{...m,interrupted:true}:m));notify('Paused. Your place in the conversation is kept.');}
 function sampleAnswer(text:string){
  if(/default|python|function|code/i.test(text)) return initialMessages[1].text;
  if(/long|explain|learn|think/i.test(text))return '**Understanding is something you can use.**\n\nThere is a difference between recognizing an explanation and being able to build with it. Career Forge is designed around that difference.\n\nStart with a small mental model. Try it against a concrete example. Then change one assumption and predict what will happen. That last step is where your understanding becomes visible.\n\n**A useful learning loop**\n\n1. Explain the idea in your own words.\n2. Make a small prediction.\n3. Write or run an example.\n4. Compare the outcome with the prediction.\n5. Keep the evidence, including the mistakes.\n\nA correct answer is one observation. A repeatable explanation, a deliberate implementation, and an independent attempt tell a richer story.\n\nWe can explore the idea in Career Forge, or take it straight into the Practice Lab.';
  return 'Let’s make space for that.\n\nWe can **think it through together**, turn it into a learning mission, or give it a concrete shape in the Practice Lab.\n\nThis conversation is a scripted frontend demonstration. Your words stay in this browser; no model or production service receives them.\n\nTry “Explain Python defaults” for a code example, or use the workspace links below to explore.';
 }
 function send(text:string){
  const value=text.trim();if(!value||streaming)return;setPrompt('');
  if(/^(continue|open|show|resume|research|what are you working)/i.test(value)){
   const route:VisionView|undefined=/career|learn/i.test(value)?'learn':/practice|lab/i.test(value)?'lab':/progress|evidence/i.test(value)?'progress':/memory/i.test(value)?'memory':/research/i.test(value)?'research':/working|objective/i.test(value)?'objectives':undefined;
   if(route){navigate(route);notify('Workspace opened · prototype context preserved');return;}
  }
  navigate('conversation');setCognition('thinking');setStreaming(true);const id=String(Date.now());
  setMessages(old=>[...old.slice(-28),{id:`u${id}`,role:'user',text:value},{id:`f${id}`,role:'friday',text:'',context:'Friday · Scripted demonstration'}]);
  stageTimer.current=setTimeout(()=>{setCognition('speaking');const answer=sampleAnswer(value);let length=0;streamTimer.current=setInterval(()=>{length=Math.min(answer.length,length+24);setMessages(old=>old.map(m=>m.id===`f${id}`?{...m,text:answer.slice(0,length)}:m));if(length>=answer.length){if(streamTimer.current)clearInterval(streamTimer.current);setStreaming(false);setCognition('idle');setVoiceDemo(false);}},28);},850);
 }
 function voice(){if(streaming||voiceDemo){interrupt();return;}setVoiceDemo(true);setCognition('listening');notify('Voice experience preview · no microphone is being recorded');stageTimer.current=setTimeout(()=>{setVoiceDemo(false);send('Explain Python defaults');},2800);}
 function renderComposer(home=false) {return <form className={`thought-composer ${home?'home-composer':''}`} onSubmit={(e:FormEvent)=>{e.preventDefault();send(prompt);}}><div className="composer-entry"><Sparkles size={17}/><textarea ref={input} value={prompt} onChange={e=>setPrompt(e.target.value)} rows={1} placeholder={home?'A question. An idea. A place to begin.':'Stay with the thought…'} aria-label="Message Friday" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(prompt);}}}/>{streaming?<button className="composer-send" type="button" onClick={interrupt} aria-label="Interrupt response"><Square size={15}/></button>:<button className="composer-send" type="submit" disabled={!prompt.trim()} aria-label="Send message"><ArrowUp size={18}/></button>}</div><div className="composer-meta"><button className={`voice-button ${voiceDemo?'voice-active':''}`} type="button" onClick={voice}><AudioLines size={15}/>{voiceDemo?'Listening preview':'Voice preview'}</button><span>{home?'Private space. Open possibilities.':'Scripted preview · browser-local conversation'}</span><kbd>↵</kbd></div></form>;}
 const learnView=['learn','map','lab','progress'].includes(view);
 return <div className={`vision-app view-${view}`} data-cognition={cognition}>
  <header className="app-header">
   <button className="brand" onClick={()=>navigate('home')} aria-label="Friday home"><Logo/><span>FRIDAY<span className="brand-dot">.</span></span></button>
   <span className="header-rule"/>
   <button className="explore-button" onClick={()=>setExplore(true)}><span>Explore</span><ChevronDown size={13}/><kbd>⌘ K</kbd></button>
   <div className="header-location">{view==='home'?'PERSONAL COGNITIVE SYSTEM':current.label.toUpperCase()}</div>
   <button className="prototype-label" onClick={()=>setInfo(true)}><i/>ASTRA VISION<span>LOCAL SIMULATION</span></button>
   <button className="icon-button attention-button" onClick={()=>setAttention(true)} aria-label="Open attention and approvals"><Bell size={18}/>{!approved&&<i/>}</button>
   <button className="avatar" onClick={()=>navigate('system')} aria-label="Your settings">R</button>
  </header>
  <div className={`presence-field ${view!=='home'?'presence-away':''}`} aria-hidden={view!=='home'}><div className="presence-aura"/><NeuralPresence state={cognition} visible={view==='home'}/></div>
  {view==='home'?<main className="home-view">
   <div className="home-coordinate"><span>01 / PRESENCE</span><span>ALWAYS YOURS.</span></div>
   <section className="home-greeting"><div className="eyebrow"><span className="tiny-line"/> A MIND AT YOUR SIDE</div><h1>Good evening,<br/><span>Rishav.</span></h1><p>There’s room for your next idea.</p><button className="home-continue" onClick={()=>navigate('learn')}><span className="continue-symbol"><BookOpen size={20}/></span><span><small>LET’S PICK UP THE THREAD</small><strong>The shape of a function</strong><em>Career Forge · Continue your mission</em></span><ArrowUpRight size={20}/></button></section>
   <div className="presence-caption"><span className="presence-indicator"/><strong>{cognitiveCopy[cognition].label}</strong><span>{cognitiveCopy[cognition].detail}</span><button onClick={()=>setStateMenu(v=>!v)} aria-label="Explore cognitive states"><MoreHorizontal size={18}/></button></div>
   <div className="home-lower">{renderComposer(true)}<nav className="home-paths" aria-label="Start a workspace"><button onClick={()=>navigate('learn')}><BookOpen size={16}/>Learn something<ArrowUpRight size={13}/></button><button onClick={()=>navigate('lab')}><Braces size={16}/>Make it work<ArrowUpRight size={13}/></button><button onClick={()=>navigate('research')}><Library size={16}/>Follow a question<ArrowUpRight size={13}/></button></nav></div>
   <footer className="home-footer"><span><span className="local-dot"/> ON YOUR MACHINE. ON YOUR TERMS.</span><button onClick={()=>setStateMenu(v=>!v)}>Explore the cognitive states <ArrowRight size={13}/></button><span>FRIDAY / VISION 01</span></footer>
  </main>:view==='conversation'?<main className="conversation-view workspace-enter">
   <header className="conversation-heading"><div><button className="back-link" onClick={()=>navigate('home')}><ArrowLeft size={14}/>Back to presence</button><h1>A thread worth following.</h1></div><div><button className="btn btn-quiet" onClick={()=>setHistory(true)}><ListFilter size={15}/>Recent threads</button><button className="icon-button" aria-label="New conversation" onClick={()=>{interrupt();setMessages([]);notify('A fresh thread. Durable prototype memories are unchanged.');}}><Plus size={18}/></button></div></header>
   <div className="conversation-scroll"><div className="thread-date"><span/>TODAY · A CONVERSATION WITH FRIDAY<span/></div>{messages.length===0?<div className="conversation-empty"><Logo/><h2>Where should we begin?</h2><p>A question is enough.</p><button className="text-link" onClick={()=>send('Explain Python defaults')}>Explore a Python idea<ArrowUpRight size={15}/></button></div>:messages.map(message=><article className={`conversation-turn turn-${message.role}`} key={message.id}><div className="turn-label">{message.role==='friday'?<Logo/>:<span className="author-mark">R</span>}<span>{message.role==='friday'?'FRIDAY':'YOU'}{message.role==='friday'&&<small>{message.context||'YOUR LOCAL COMPANION'}</small>}</span></div>{!message.text?<div className="thinking-dots"><i/><i/><i/><span>Finding the thread…</span></div>:<RichText text={message.text}/>} {message.interrupted&&<span className="interrupted-label">Response interrupted · retained here for context</span>}</article>)}<div ref={readEnd}/>{!streaming&&messages.length>0&&<div className="conversation-next"><span>TAKE THE THOUGHT FURTHER</span><button onClick={()=>navigate('learn')}>Continue in Career Forge<ArrowUpRight size={14}/></button><button onClick={()=>navigate('lab')}>Try it in Practice Lab<ArrowUpRight size={14}/></button></div>}</div>
   <div className="conversation-bottom"><button className="jump-latest" onClick={()=>readEnd.current?.scrollIntoView({behavior:'smooth'})} aria-label="Jump to latest message"><ArrowDown size={15}/></button>{renderComposer()}</div>
  </main>:<main className={`workspace-host workspace-enter ${view==='lab'?'studio-host':''}`} key={view}><div className="workspace-topline"><button className="back-link" onClick={()=>navigate('home')}><ArrowLeft size={14}/>Friday</button><span>/</span><span>{learnView?'CAREER FORGE':current.group.toUpperCase()}</span><div className="workspace-presence"><i/>{cognitiveCopy[cognition].label}<button onClick={()=>navigate('conversation')}><AudioLines size={14}/><span>Talk to Friday</span></button></div></div><Suspense fallback={<div className="workspace-loading"><LoaderCircle size={20}/>Opening your workspace…</div>}>{learnView?<Learning view={view as 'learn'|'map'|'lab'|'progress'} {...workProps}/>:<Operations view={view as 'memory'|'research'|'objectives'|'automations'|'perception'|'system'} {...workProps}/>}</Suspense></main>}
  {stateMenu&&<div className="cognitive-menu"><div className="menu-heading"><span>COGNITIVE STATES</span><button className="icon-button" aria-label="Close cognitive states" onClick={()=>setStateMenu(false)}><X size={15}/></button></div><p>Explore how a thought takes shape.</p>{(Object.keys(cognitiveCopy) as CognitiveState[]).map(state=><button key={state} aria-pressed={state===cognition} onClick={()=>setCognition(state)}><span className={`state-glyph glyph-${state}`}><i/><i/><i/></span><span><strong>{cognitiveCopy[state].label}</strong><small>{state==='idle'?'Idle':state==='focus'?'Deep focus':state[0].toUpperCase()+state.slice(1)}</small></span>{state===cognition&&<Check size={15}/>}</button>)}<small className="demo-footnote">Visual state preview · no runtime action</small></div>}
  {explore&&<Modal label="Explore Friday" wide onClose={()=>setExplore(false)}><div className="explore-search"><Search size={21}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Where would you like to go?" aria-label="Search workspaces"/><button className="key-button" onClick={()=>setExplore(false)}>ESC</button></div><div className="explore-body"><div className="destination-list">{destinations.filter(d=>`${d.label} ${d.description} ${d.group}`.toLowerCase().includes(query.toLowerCase())).map((d,i,all)=><div key={d.id}>{(i===0||d.group!==all[i-1].group)&&<div className="nav-group-label">{d.group}</div>}<button className={view===d.id?'selected':''} onClick={()=>navigate(d.id)}><d.icon size={19}/><span><strong>{d.label}</strong><small>{d.description}</small></span><ArrowUpRight size={15}/></button></div>)}{destinations.filter(d=>`${d.label} ${d.description} ${d.group}`.toLowerCase().includes(query.toLowerCase())).length===0&&<p className="no-results">No workspace matches. Try “learn”, “memory”, or “research”.</p>}</div><aside className="explore-aside"><div className="eyebrow">YOUR CONTINUING STORY</div><div className="explore-orbit"><Logo/></div><h2>Small steps.<br/>Deeper understanding.</h2><p>Your learning, ideas, and work share one space.</p><button className="text-link" onClick={()=>navigate('learn')}>Resume your mission<ArrowRight size={16}/></button><div className="explore-note"><ShieldCheck size={18}/><p>Everything in this vision is a local demonstration. Your current Friday remains separate.</p></div></aside></div><div className="explore-footer"><span><Command size={12}/> K to explore · Escape to return</span><span>ONE FRIDAY. MANY POSSIBILITIES.</span></div></Modal>}
  {attention&&<Modal label="Your attention" onClose={()=>{setAttention(false);setReview(false);}}><div className="drawer-heading"><div className="eyebrow">JUST WHAT MATTERS</div><button className="icon-button" aria-label="Close attention" onClick={()=>{setAttention(false);setReview(false);}}><X size={19}/></button></div><div className="attention-content"><Bell size={25}/><h2>Your attention.</h2><p>One considered decision. The rest can wait.</p>{!approved?<div className="attention-item"><span className="status status-amber"><i/>Your decision</span><h3>Open the research source?</h3><p>Friday has prepared a browser action for a source in your research notebook.</p>{review?<div className="approval-preview"><div className="detail-row"><span>Action</span><span>Open website</span></div><div className="detail-row"><span>Destination</span><span>docs.python.org</span></div><div className="detail-row"><span>Authority</span><span>This action only</span></div><p>No website will open in this prototype.</p><div className="button-row"><button className="btn btn-primary" onClick={()=>{setApproved(true);setReview(false);notify('Demo action approved · nothing was opened or executed');}}>Approve preview<Check size={16}/></button><button className="btn" onClick={()=>{setApproved(true);setReview(false);notify('Demo action declined');}}>Decline</button></div></div>:<button className="text-link" onClick={()=>setReview(true)}>Review the action<ArrowUpRight size={16}/></button>}</div>:<div className="attention-resolved"><Check size={28}/><h3>Nothing needs a decision.</h3><p>Your demonstration decision has been recorded locally.</p><button className="text-link" onClick={()=>setApproved(false)}>Reset this preview</button></div>}<div className="attention-event"><span className="tiny-line"/><div><small>LEARNING · EARLIER TODAY</small><p>A new piece of evidence is ready to explore.</p><button className="text-link" onClick={()=>{setAttention(false);navigate('progress');}}>See your progress<ArrowUpRight size={14}/></button></div></div></div></Modal>}
  {info&&<Modal label="About this vision" onClose={()=>setInfo(false)}><div className="drawer-heading"><div className="eyebrow">ASTRA VISION / 01</div><button className="icon-button" aria-label="Close about" onClick={()=>setInfo(false)}><X size={18}/></button></div><div className="about-content"><Logo/><h2>One Friday.<br/>An open possibility.</h2><p>This is a complete interactive frontend vision. Conversations, learning results, memory, research, voice, captures, and actions use representative data and browser-local state.</p><p>No production model, microphone, desktop, database, or Friday API is connected. Code outcomes are simulated, not executed.</p><div className="about-links"><span>Current Friday</span><a href="http://localhost:5173" target="_blank" rel="noreferrer">localhost:5173<ArrowUpRight size={14}/></a></div><button className="btn btn-primary" onClick={()=>setInfo(false)}>Explore the vision<ArrowRight size={16}/></button></div></Modal>}
  {history&&<Modal label="Recent conversations" onClose={()=>setHistory(false)}><div className="drawer-heading"><div className="eyebrow">RECENT THREADS</div><button className="icon-button" aria-label="Close recent threads" onClick={()=>setHistory(false)}><X size={18}/></button></div><div className="history-content"><h2>Pick up a thought.</h2><p>Example threads. Separate from durable memory.</p>{[{title:'The surprising life of a default',subtitle:'Python · A code example',text:'Explain Python defaults'},{title:'How understanding becomes evidence',subtitle:'Learning · A longer reflection',text:'Explain how to learn deeply'}].map(thread=><button className="history-thread" key={thread.title} onClick={()=>{setHistory(false);setMessages([{id:'history-u',role:'user',text:thread.text},{id:'history-f',role:'friday',text:sampleAnswer(thread.text),context:'Example thread'}]);}}><span><strong>{thread.title}</strong><small>{thread.subtitle}</small></span><ArrowUpRight size={17}/></button>)}</div></Modal>}
  {toast&&<div className="toast" role="status"><Check size={16}/><span>{toast}</span><button onClick={()=>setToast('')} aria-label="Dismiss notification"><X size={14}/></button></div>}
 </div>;
}
